# Generated by Django 5.0.1 on 2024-06-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pestName', models.CharField(max_length=200)),
                ('diseaseName', models.CharField(max_length=200)),
                ('countyName', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
