# Generated by Django 5.0.1 on 2024-09-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='reports',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
